[package]
name = "ai-terminal"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
dirs-next = "2.0.0"
reqwest = { version = "0.12.14", features = ["json", "blocking"] }
serde = { version = "1.0", features = ["derive"] }
