name: Release

on:
  push:
    branch:
      "master"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd ai-terminal
          npm ci

      - name: Build
        run: |
          cd ai-terminal
          npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Sign macOS app
      #   if: matrix.os == 'macos-latest'
      #   run: |
      #     # Add your code signing steps here
      #     # Example: codesign --force --sign "Developer ID Application: Your Name (TEAM_ID)" dist/your-app.app
      #   env:
      #     APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
      #     APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}

      - name: Generate tag
        run: |
          cd ai-terminal
          VERSION=$(node -p "require('./package.json').version")
          echo "RELEASE_TAG=v${VERSION}" >> $GITHUB_ENV

      - name: Create and push tag
        run: |
          git tag ${{ env.RELEASE_TAG }}
          git push origin ${{ env.RELEASE_TAG }}

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          files: |
            ai-terminal/dist/**/*.AppImage
            ai-terminal/dist/**/*.dmg
            ai-terminal/dist/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
