name: Release

on:
  push:
    branch:
      "master"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install create-dmg (macOS only)
        if: matrix.os == 'macos-latest'
        run: brew install create-dmg

      - name: Install dependencies
        run: |
          cd ai-terminal
          npm ci

      - name: Build macOS Universal
        if: matrix.os == 'macos-latest'
        run: |
          cd ai-terminal
          chmod +x build-macos.sh
          ./build-macos.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate tag
        run: |
          cd ai-terminal
          VERSION=$(node -p "require('./package.json').version")
          echo "RELEASE_TAG=v${VERSION}" >> $GITHUB_ENV

      - name: Create and push tag
        run: |
          git tag ${{ env.RELEASE_TAG }}
          git push origin ${{ env.RELEASE_TAG }}

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          files: |
            ai-terminal/src-tauri/target/universal-apple-darwin/bundle/dmg/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
