name: Build and Release

on:
  push:
    branches: [ master ]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin, x86_64-apple-darwin
      
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        
      - name: Install cargo-bundle
        run: cargo install cargo-bundle
      
      - name: Build for x86_64
        run: |
          cd ai-terminal
          cargo build --release --target x86_64-apple-darwin
      
      - name: Build for aarch64
        run: |
          cd ai-terminal
          cargo build --release --target aarch64-apple-darwin
      
      - name: Create Universal Binary
        run: |
          cd ai-terminal
          mkdir -p target/release
          lipo -create \
            target/x86_64-apple-darwin/release/ai-terminal \
            target/aarch64-apple-darwin/release/ai-terminal \
            -output target/release/ai-terminal
      
      - name: Create App Bundle
        run: |
          cd ai-terminal
          # Use the default target for bundle creation
          cargo bundle --release
          
      - name: Create DMG
        run: |
          cd ai-terminal
          # Install create-dmg and ImageMagick
          brew install create-dmg imagemagick
          
          # Create a basic background if it doesn't exist
          if [ ! -f "icons/dmg-background.png" ]; then
            mkdir -p icons
            # Create a simple colored background
            convert -size 800x500 -gravity center gradient:gray10-gray30 \
              -fill white -pointsize 24 -annotate 0 "AI Terminal" \
              icons/dmg-background.png
          fi
          
          # Create DMG from the .app bundle
          create-dmg \
            --volname "AI Terminal" \
            --background "icons/dmg-background.png" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "AI Terminal.app" 200 190 \
            --app-drop-link 600 185 \
            "target/release/AI-Terminal-Installer.dmg" \
            "target/release/bundle/osx/AI Terminal.app" || \
          # Fallback if the above fails (perhaps due to background image issues)
          create-dmg \
            --volname "AI Terminal" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "AI Terminal.app" 200 190 \
            --app-drop-link 600 185 \
            "target/release/AI-Terminal-Installer.dmg" \
            "target/release/bundle/osx/AI Terminal.app"
      
      - name: Upload macOS app artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: ai-terminal/target/release/bundle/osx/*.app
          retention-days: 7
          
      - name: Upload macOS DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-dmg
          path: ai-terminal/target/release/AI-Terminal-Installer.dmg
          retention-days: 7
  
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
      
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      
      - name: Install cargo-bundle
        run: cargo install cargo-bundle
      
      - name: Build DEB package
        run: |
          cd ai-terminal
          cargo bundle --release --format deb
      
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-deb
          path: ai-terminal/target/release/bundle/deb/*.deb
          retention-days: 7
