name: Build and Release

on:
  push:
    branches: [ master ]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin, x86_64-apple-darwin
      
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        
      - name: Install cargo-bundle
        run: cargo install cargo-bundle
      
      - name: Build Universal Binary
        run: |
          cd ai-terminal
          cargo build --release --target x86_64-apple-darwin
          cargo build --release --target aarch64-apple-darwin
          mkdir -p target/universal-apple-darwin/release
          lipo -create \
            target/x86_64-apple-darwin/release/ai-terminal \
            target/aarch64-apple-darwin/release/ai-terminal \
            -output target/universal-apple-darwin/release/ai-terminal
      
      - name: Create DMG
        run: |
          cd ai-terminal
          cargo bundle --release --target universal-apple-darwin
          
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-dmg
          path: ai-terminal/target/universal-apple-darwin/release/bundle/dmg/*.dmg
          retention-days: 7
  
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
      
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      
      - name: Install cargo-bundle
        run: cargo install cargo-bundle
      
      - name: Build DEB package
        run: |
          cd ai-terminal
          cargo bundle --release --format deb
      
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-deb
          path: ai-terminal/target/release/bundle/deb/*.deb
          retention-days: 7
